### ISSUE TITLE
tag0.4.3 won't generate valid json

### ISSUE THREAD

**Issue by tsingakbar** [grailbio/bazel-compilation-database#52]
because the last object in the root array ends with a comma(,)
then vscode will fail to parse it.

**Comment by siddharthab** [comment]
Sorry, my fault. I think it's fixed in master. Let me tag it as 0.4.4.

**Comment by siddharthab** [comment]
New version released with a5d4bd3270d460f3b9ebdd35a756b65f4e8046e2.

**Comment by nabroyan** [comment]
@siddharthab I just tried with 0.4.4 tag and I still get redundant commas.

My steps:
1. Downloaded tar.gz of 0.4.4 tag, extracted.
2. From my repo I called the `generate.sh` script like `path_to_the_folder/bazel-compilation-database-0.4.4/generate.sh target_name`
After this I get the `compile_commands.json`, but with some extra lines, which only contains a single comma.

Any suggestions?
